name: music-box
on:
  schedule:
    - cron: '0 * * * *'  # hourly
  workflow_dispatch:
jobs:
  musicbox:
   runs-on: ubuntu-latest
   steps: 
    - uses: jacc/music-box@master
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with: 
        node-version: "14.x"
    - name: Install dependencies
      run: npm install
      env:
          LASTFM_KEY: ${{ secrets.LASTFM_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LFMUSERNAME: ${{ secrets.LFMUSERNAME }}
          GIST_ID: ${{ secrets.GIST_ID }}
