name: music-box
on:
  schedule:
    - cron: '0 * * * *'  # hourly
  push:
    branches: master
jobs:
  musicbox:
   runs-on: ubuntu-latest
   steps:
     - uses: jacc/music-box@master
       with:
          LASTFM_KEY: ${{ secrets.LASTFM_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LFMUSERNAME: ${{ secrets.LFMUSERNAME }}
          GIST_ID: ${{ secrets.GIST_ID }}
