name: music-box
on:
  schedule:
    - cron: '0 * * * *'  # hourly
  workflow_dispatch:
jobs:
  musicbox:
   runs-on: ubuntu-latest
   strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]
   steps:
     - uses: actions/checkout@v2
     - name: Update
     - uses: actions/setup-node@v3
     - with:
         node-version: ${{ matrix.node-version }}
     - uses: jacc/music-box@master
     - run: npm install
     - with:
          LASTFM_KEY: ${{ secrets.LASTFM_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LFMUSERNAME: ${{ secrets.LFMUSERNAME }}
          GIST_ID: ${{ secrets.GIST_ID }}
