name: Update stats

on:
  schedule:
    - cron: '2 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          API_BASE_URL: https://wakapi.dev/api
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN}}
          SHOW_TITLE: false
          BLOCKS: ▱▰
          TIME_RANGE: all_time
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
