name: WakaTime Readme

on:
  schedule:
    - cron: '2 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: WakaTime Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          API_BASE_URL: ${{ secrets.WAKATIME_API_BASE_URL }}
          SHOW_TITLE: false
          BLOCKS: ▱▰
          TIME_RANGE: all_time
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
